typeset -U path
path=(~/bin $path[@])

# Android Studio environment variables needed by React-Native
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

alias avd-react-native='"${ANDROID_HOME}/tools/emulator" -avd react-native-3'
